from rest_framework import serializers

class BusinessPartnerSerializer(serializers.Serializer):
    bpCode = serializers.CharField(max_length = 10)
    bpName = serializers.CharField(max_length = 100)
    bpTradeName = serializers.CharField(max_length = 100, allow_null=True, required=False)
    bpConnected = serializers.CharField(max_length = 10, allow_null=True, required=False)
    bpGSTType = serializers.CharField(max_length = 1)
    bpGSTIN = serializers.CharField(max_length = 15, allow_null=True, required=False)
    ctid = serializers.CharField(max_length = 2)
    bpType = serializers.CharField(max_length = 1)
    bpAdd = serializers.CharField(max_length = 100)
    bpAdd1 = serializers.CharField(max_length = 100, allow_null=True, required=False)
    bpCity = serializers.CharField(max_length = 50)
    bpState = serializers.IntegerField()
    bpZipCode = serializers.CharField(max_length = 6)
    bpCountry = serializers.CharField(max_length = 2)
    bpPhone = serializers.CharField(max_length = 10)
    bpWhatsApp = serializers.CharField(max_length = 10, allow_null=True, required=False)
    bpEmail = serializers.CharField(max_length = 50, allow_null=True, required=False)
    contactPerson = serializers.CharField(max_length = 50, allow_null=True, required=False)
    designation = serializers.CharField(max_length = 20, allow_null=True, required=False)
    #crDays = serializers.IntegerField()
    paymentTerm = serializers.CharField(max_length = 100, allow_null=True, required=False)
    #packing = serializers.CharField(max_length = 1)
    #freight = serializers.CharField(max_length = 1)
    #insurance = serializers.CharField(max_length = 1)
    #insurancePaid = serializers.CharField(max_length = 1)
    tcsEnabled = serializers.CharField(max_length = 1, allow_null=True, required=False)
    itcCreditable = serializers.CharField(max_length = 1)
    cin = serializers.CharField(max_length = 20, allow_null=True, required=False)
    pan = serializers.CharField(max_length = 20, allow_null=True, required=False)
    tan = serializers.CharField(max_length = 20, allow_null=True, required=False)
    pfno = serializers.CharField(max_length = 20, allow_null=True, required=False)
    esino = serializers.CharField(max_length = 20, allow_null=True, required=False)
    mop = serializers.CharField(max_length = 1, allow_null=True, required=False)
    bankAcType = serializers.CharField(max_length = 20, allow_null=True, required=False)
    bankAcNo = serializers.CharField(max_length = 20, allow_null=True, required=False)
    bankAcName = serializers.CharField(max_length = 50, allow_null=True, required=False)
    bankName = serializers.CharField(max_length = 50, allow_null=True, required=False)
    bankBranch = serializers.CharField(max_length = 100, allow_null=True, required=False)
    ifscCode = serializers.CharField(max_length = 11, allow_null=True, required=False)
    swiftCode = serializers.CharField(max_length = 20, allow_null=True, required=False)
    R_Tcs = serializers.DecimalField(default = 0, max_digits=12, decimal_places=2)
    brType = serializers.CharField(max_length = 1)
    discType = serializers.CharField(max_length = 1)
    discRate = serializers.DecimalField(default = 0, max_digits=12, decimal_places=2)
    loyaltyDisc = serializers.DecimalField(default = 0, max_digits=12, decimal_places=2)
    paymentDisc = serializers.DecimalField(default = 0, max_digits=12, decimal_places=2)
    slId = serializers.CharField(max_length=2)
    stId = serializers.CharField(max_length=1)
    tdsCode = serializers.CharField(max_length=10)
    bpDistance = serializers.IntegerField()