from rest_framework import serializers

class GrIqsRepSerializer(serializers.Serializer):
    grdId = serializers.IntegerField()
    lotSize = serializers.IntegerField()
    sampleSize = serializers.IntegerField()
    machineno = serializers.CharField(max_length=15, allow_null=True, required=False)
    defect = serializers.CharField(max_length=40, allow_null=True, required=False)
    defectDescription = serializers.CharField(max_length=100, allow_null=True, required=False)
    suggestion = serializers.CharField(max_length=100, allow_null=True, required=False)
    testType = serializers.CharField(max_length=30)
    testItem = serializers.CharField(max_length=30)
    testName = serializers.CharField(max_length=30, allow_null=True, required=False)
    instName = serializers.CharField(max_length=30, allow_null=True, required=False)
    lowerLimit = serializers.CharField(max_length=20)
    higherLimit = serializers.CharField(max_length=20)
    ov1 = serializers.CharField(max_length=20, allow_null=True, required=False)
    ov2 = serializers.CharField(max_length=20, allow_null=True, required=False)
    ov3 = serializers.CharField(max_length=20, allow_null=True, required=False)
    ov4 = serializers.CharField(max_length=20, allow_null=True, required=False)
    ov5 = serializers.CharField(max_length=20, allow_null=True, required=False)
    ov6 = serializers.CharField(max_length=20, allow_null=True, required=False)
    ov7 = serializers.CharField(max_length=20, allow_null=True, required=False)
    ov8 = serializers.CharField(max_length=20, allow_null=True, required=False)
    ov9 = serializers.CharField(max_length=20, allow_null=True, required=False)
    ov10 = serializers.CharField(max_length=20, allow_null=True, required=False)
    remark = serializers.CharField(max_length=100)
    qcStatus = serializers.IntegerField(default=0)
    checkedBy = serializers.IntegerField()