"""
Django settings for CaFinTech project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3&+vud7==_ucb88e#)6z_t4lhtqe+!15-etghaq!d&-5m^3!n-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cafintech_api',
    'user',
    'rest_framework',
    'crispy_forms',
    'corsheaders',
    'oauth2_provider',    
    'crispy_bootstrap5',
    'drf_yasg',
    'fintech_reports',

    # TWO FACTOR

    "django_otp",
    "django_otp.plugins.otp_static",
    "django_otp.plugins.otp_totp",
    "two_factor",
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django_otp.middleware.OTPMiddleware',  # OTP Middleware
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CaFinTech.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CaFinTech.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'masterDb',
        'HOST': '36.255.3.34,15666',
        'USER': 'usr365',
        'PASSWORD': 'Pmc&$!@0011733',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
       }
    },
    'SA': {
        'ENGINE': 'mssql',
        'NAME': 'SARemoteMDb',
        'HOST': '36.255.3.34,15666',
        'USER': 'usr365',
        'PASSWORD': 'Pmc&$!@0011733',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
       }
    },
    'SE': {
        'ENGINE': 'mssql',
        'NAME': 'SERemoteMDb',
        'HOST': '36.255.3.34,15666',
        'USER': 'usr365',
        'PASSWORD': 'Pmc&$!@0011733',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
       }
    },
    'SU': {
        'ENGINE': 'mssql',
        'NAME': 'SLRemoteMDb',
        'HOST': '36.255.3.34,15666',
        'USER': 'usr365',
        'PASSWORD': 'Pmc&$!@0011733',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
       }
    },
    'SR': {
        'ENGINE': 'mssql',
        'NAME': 'STRemoteMDb',
        'HOST': '36.255.3.34,15666',
        'USER': 'usr365',
        'PASSWORD': 'Pmc&$!@0011733',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
       }
    },
    'OW': {
        'ENGINE': 'mssql',
        'NAME': 'PurchaseMdb',
        'HOST': '103.205.67.16,15333',
        'USER': 'sa',
        'PASSWORD': 'Tstsql@1234',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
       }
    },
    'SW': {
        'ENGINE': 'mssql',
        'NAME': 'SWLiveDb',
        'HOST': '36.255.3.34,15666',
        'USER': 'usr365',
        'PASSWORD': 'Pmc&$!@0011733',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
       }
    },
    'EM': {
        'ENGINE': 'mssql',
        'NAME': 'EMLiveDb',
        'HOST': '36.255.3.34,15666',
        'USER': 'usr365',
        'PASSWORD': 'Pmc&$!@0011733',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
       }
    },
    'EL': {
        'ENGINE': 'mssql',
        'NAME': 'ELLiveDb',
        'HOST': '36.255.3.34,15666',
        'USER': 'usr365',
        'PASSWORD': 'Pmc&$!@0011733',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
       }
    },
    'ST': {
        'ENGINE': 'mssql',
        'NAME': 'STLiveDb',
        'HOST': '36.255.3.34,15666',
        'USER': 'usr365',
        'PASSWORD': 'Pmc&$!@0011733',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
       }
    },
    'SS': {
        'ENGINE': 'mssql',
        'NAME': 'SSLiveDb',
        'HOST': '36.255.3.34,15666',
        'USER': 'usr365',
        'PASSWORD': 'Pmc&$!@0011733',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
       }
    },
    'SL': {
        'ENGINE': 'mssql',
        'NAME': 'SLLiveDb',
        'HOST': '36.255.3.34,15666',
        'USER': 'usr365',
        'PASSWORD': 'Pmc&$!@0011733',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
       }
    },
    'SI': {
        'ENGINE': 'mssql',
        'NAME': 'SILiveDb',
        'HOST': '36.255.3.34,15666',
        'USER': 'usr365',
        'PASSWORD': 'Pmc&$!@0011733',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
       }
    },
    'ED': {
        'ENGINE': 'mssql',
        'NAME': 'EMDLiveDb',
        'HOST': '36.255.3.34,15666',
        'USER': 'usr365',
        'PASSWORD': 'Pmc&$!@0011733',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
       }
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-in'

TIME_ZONE = 'UTC+05:30'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'

AUTH_USER_MODEL = 'user.User'
DATA_UPLOAD_MAX_NUMBER_FIELDS = None

# OIDC_KEY = Path(str(BASE_DIR) + "/oidc.key").read_text()
# OAUTH2_PROVIDER = {
#     "OIDC_ENABLED": True,
#     "OIDC_RSA_PRIVATE_KEY": OIDC_KEY,
#     "SCOPES": {"all": "all scopes"},
# }

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # "oauth2_provider.contrib.rest_framework.OAuth2Authentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ]
}


CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_METHODS = (
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
)

LOGIN_URL = '/admin/login/'
LOGIN_REDIRECT_URL = '/'
APPEND_SLASH = True

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME" : timedelta(days=7),
    "USER_ID_FIELD" : "userId"
}

MEDIA_ROOT = os.path.join(BASE_DIR, 'docs')
MEDIA_URL = '/media/'

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Basic': {
            'type': 'basic'
        }
    }
}

path_wkhtmltopdf = r'C:\\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe'
File_Path = r'D:\sd\\fintech_api\\api\\CaFinTech\\docs\\docs'


EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'heroup534@gmail.com'         # your Gmail address
EMAIL_HOST_PASSWORD = 'kvcrdcswxtdxupcf'   # use App Password (not your Gmail password)

X_FRAME_OPTIONS = 'ALLOW-FROM *'

FERNET_KEY = 'LvFBgaOkI7H0Mm1RvqU6VV-rLVUTyLJClLB6z0HwbtE='