# Generated by Django 4.2.11 on 2026-02-21 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('userId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=60, verbose_name='email')),
                ('roles', models.CharField(max_length=50)),
                ('cid', models.CharField(blank=True, max_length=5, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_code', models.IntegerField()),
                ('error_message', models.TextField()),
                ('error_time', models.DateTimeField(auto_now_add=True)),
                ('api_method_type', models.TextField(default='POST')),
                ('api_endpoint', models.TextField()),
                ('api_payload', models.TextField(blank=True, null=True)),
                ('ip_address', models.TextField()),
                ('user_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FlutterForm',
            fields=[
                ('id', models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(max_length=50, unique=True)),
                ('form_description', models.CharField(max_length=200)),
                ('form_fields', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('role_description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyGroup',
            fields=[
                ('group_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('group_description', models.CharField(max_length=30)),
                ('associated_companies', models.CharField(max_length=250)),
                ('associated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('cid', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('connection_string', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='cgId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.companygroup'),
        ),
    ]
