# Generated by Django 4.2.11 on 2024-10-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('cid', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
