# Generated by Django 4.2.11 on 2024-10-25 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.company'),
            preserve_default=False,
        ),
    ]
