# Generated by Django 4.2.11 on 2024-10-25 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.company', verbose_name='cid'),
        ),
    ]
