# Generated by Django 4.2.11 on 2025-03-30 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('role_description', models.CharField(max_length=30)),
            ],
        )
    ]
