# Generated by Django 4.2.11 on 2025-07-26 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_errorlog_alter_user_roles_alter_user_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlutterForm',
            fields=[
                ('id', models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(max_length=50, unique=True)),
                ('form_description', models.CharField(max_length=200)),
                ('form_fields', models.TextField()),
            ],
        )
    ]
