# Generated by Django 4.2.11 on 2025-08-07 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_flutterform_alter_user_roles_alter_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ForeignKey(default='US', on_delete=django.db.models.deletion.CASCADE, to='user.roles', verbose_name='roles'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
