# Generated by Django 4.2.11 on 2026-02-19 10:59

import cafintech_api.models.upload
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillReceiptUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=cafintech_api.models.upload.dynamic_upload_to)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=cafintech_api.models.upload.dynamic_upload_to)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='docs')),
                ('drawing', models.FileField(blank=True, null=True, upload_to='drawings')),
            ],
        ),
        migrations.CreateModel(
            name='JsonForm',
            fields=[
                ('form_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('form_description', models.TextField()),
                ('form_data', models.JSONField()),
                ('procedure_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JvoucherUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=cafintech_api.models.upload.dynamic_upload_to)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
