# Generated by Django 4.2.11 on 2024-11-13 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafintech_api', '0002_fileupload_delete_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HSN',
        ),
    ]
