# Generated by Django 4.2.11 on 2025-06-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafintech_api', '0003_delete_hsn'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='drawing',
            field=models.FileField(blank=True, null=True, upload_to='drawings'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='docs'),
        ),
    ]
