# Generated by Django 4.2.11 on 2025-08-07 15:26

import cafintech_api.models.upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafintech_api', '0004_fileupload_drawing_alter_fileupload_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillReceiptUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=cafintech_api.models.upload.dynamic_upload_to)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
